import arcade

WINDOW_WIDTH = 800
WINDOW_HEIGHT = 600
BACKGROUND_COLOR = arcade.color.BLACK

MAIN_TITLE = "Jeopardy"
MAIN_TITLE_COLOR = arcade.color.YELLOW

NUM_CATEGORIES = 6
NUM_QUESTIONS_PER_CATEGORY = 5

BOX_PADDING = 10

MESSAGE_BOX_HEIGHT = 150
TEAM_DISPLAY_HEIGHT = 50