import arcade

######################################
#         Jeopardy Constants         # 
######################################
WINDOW_WIDTH = 800
WINDOW_HEIGHT = 600

DEFAULT_BACKGROUND_COLOR = (0, 0, 0)
DEFAULT_FOREGROUND_COLOR = (3, 31, 96)
DEFAULT_TEXT_COLOR = (249, 190, 16)

MAIN_TITLE = "Jeopardy"
MAIN_TITLE_COLOR = arcade.color.YELLOW

BOX_PADDING = 10

DEFAULT_BUTTON_WIDTH = 125
DEFAULT_BUTTON_HEIGHT = 75

MESSAGE_BOX_HEIGHT = 150
TEAM_DISPLAY_HEIGHT = 50

MAX_TEAMNAME_CHARS = 10
MIN_NUM_TEAMS = 2
MAX_NUM_TEAMS = 5
