import arcade

WINDOW_WIDTH = 800
WINDOW_HEIGHT = 600
BACKGROUND_COLOR = arcade.color.BLACK

MAIN_TITLE = "Jeopardy"
MAIN_TITLE_COLOR = arcade.color.YELLOW

BOX_PADDING = 10

MESSAGE_BOX_HEIGHT = 150
TEAM_DISPLAY_HEIGHT = 50

MAX_TEAMNAME_CHARS = 10
MIN_NUM_TEAMS = 2
MAX_NUM_TEAMS = 5